ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "pesoLiquido"  DECIMAL(10,3);
ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "pesoBruto"    DECIMAL(10,3);
ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "largura"      DECIMAL(10,2);
ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "altura"       DECIMAL(10,2);
ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "profundidade" DECIMAL(10,2);
ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "numeroPeca"   TEXT;
