CREATE TABLE IF NOT EXISTS "ShopeeCategoria" (
    "id" INTEGER NOT NULL,
    "categoria" TEXT NOT NULL,
    "subcategoria" TEXT NOT NULL,
    "nivel3" TEXT NOT NULL DEFAULT '',
    "nivel4" TEXT NOT NULL,
    "permitido" BOOLEAN NOT NULL DEFAULT true,
    "atualizadoEm" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "ShopeeCategoria_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "ShopeeCategoria_nivel4_idx" ON "ShopeeCategoria"("nivel4");

CREATE TABLE IF NOT EXISTS "CategoriaVinculoMarketplace" (
    "id" SERIAL NOT NULL,
    "categoriaBlingId" INTEGER NOT NULL,
    "marketplace" TEXT NOT NULL,
    "codigoExterno" TEXT NOT NULL,
    "descricaoExterno" TEXT NOT NULL DEFAULT '',
    "atualizadoEm" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "CategoriaVinculoMarketplace_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "CategoriaVinculoMarketplace_categoriaBlingId_marketplace_key" ON "CategoriaVinculoMarketplace"("categoriaBlingId", "marketplace");

-- Arvore oficial da Shopee (Product Mapping > Categories), capturada manualmente em 29/09/2026.
INSERT INTO "ShopeeCategoria" ("id","categoria","subcategoria","nivel3","nivel4","permitido","atualizadoEm") VALUES
(102433,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Kit de Plásticos',true,now()),
(102434,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Amortecedores',false,now()),
(102435,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Freios',false,now()),
(102436,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Guidão e Componentes',true,now()),
(102437,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Paralamas',true,now()),
(102438,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Cavaletes',true,now()),
(102439,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Bengalas',true,now()),
(102440,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Chaves',true,now()),
(102441,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Maçanetas',true,now()),
(102442,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Cabos',true,now()),
(102443,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Bancos',true,now()),
(102444,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Suportes de Placas',true,now()),
(102445,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Tampas de Tanques',true,now()),
(102446,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Cubo de Roda',true,now()),
(102447,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Raios',true,now()),
(102448,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Pedaleiras',true,now()),
(102449,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Manoplas',true,now()),
(102450,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Protetores de Motor',true,now()),
(102451,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Alças',true,now()),
(102452,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Tanque de Combustível',true,now()),
(102453,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Outros',true,now()),
(102599,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Chassis','Guidão e Componentes',true,now()),
(102454,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Cilindros',true,now()),
(102455,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Carburadores',true,now()),
(102456,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Cabeçotes',true,now()),
(102457,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Peças de Partida',true,now()),
(102458,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Pistões',true,now()),
(102459,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Correntes de Transmissão',true,now()),
(102460,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Estatores',true,now()),
(102461,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Árvores Comando de Válvulas',true,now()),
(102462,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Bielas',true,now()),
(102463,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Regulador Retificador',true,now()),
(102464,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Tensor Corrente de Comando',true,now()),
(102465,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Bomba de Óleo',true,now()),
(102466,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Motor','Outros',true,now()),
(102467,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Transmissão','Kit de Transmissão',true,now()),
(102468,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Transmissão','Embreagens',true,now()),
(102469,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Transmissão','Coroas',true,now()),
(102470,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Transmissão','Caixas de Marchas',true,now()),
(102471,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Transmissão','Eixos de Câmbio',true,now()),
(102472,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Transmissão','Correia de Transmissão',true,now()),
(102473,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Transmissão','Outros',true,now()),
(102474,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Escape e Silenciador','Escapamentos',true,now()),
(102475,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Escape e Silenciador','Silenciador',true,now()),
(102476,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Escape e Silenciador','Outros',true,now()),
(102477,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Iluminação','Luzes de Sinalização',true,now()),
(102478,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Iluminação','Faróis',true,now()),
(102479,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Iluminação','Farol Baixo',true,now()),
(102480,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Iluminação','Outros',true,now()),
(102481,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Ignição','CDI',true,now()),
(102482,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Ignição','Chaves de Ignição',true,now()),
(102483,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Ignição','Velas',true,now()),
(102484,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Ignição','Bobina de Ignição',true,now()),
(102485,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Ignição','Outros',true,now()),
(102486,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Filtros','Filtros de Ar',true,now()),
(102487,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Filtros','Filtros de Óleo',true,now()),
(102488,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Filtros','Kit de Filtros',true,now()),
(102489,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Filtros','Outros',true,now()),
(102490,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','Aditivos e Lubrificantes','Óleos de Motor',true,now()),
(102537,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','','Espelhos Retrovisores',true,now()),
(102538,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','','Baterias',false,now()),
(102539,'Peças e Acessórios para Veículos','Peças de Reposição para Motocicletas','','Outros',true,now()),
(102491,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Indumentária e Calçado','Capas de Chuva',true,now()),
(102492,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Indumentária e Calçado','Jaquetas',true,now()),
(102493,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Indumentária e Calçado','Botas',true,now()),
(102494,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Indumentária e Calçado','Acessórios',true,now()),
(102495,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Indumentária e Calçado','Proteção para Motociclistas',true,now()),
(102496,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Indumentária e Calçado','Outros',true,now()),
(102497,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Baús','Baús Traseiros',true,now()),
(102498,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Baús','Bagageiros',true,now()),
(102499,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Baús','Baús Laterais',true,now()),
(102500,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Baús','Outros',true,now()),
(102501,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Capas','Capas para Motos',true,now()),
(102502,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Capas','Capas para Bancos',true,now()),
(102503,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','Capas','Outros',true,now()),
(102540,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Protetor de Motor',true,now()),
(102541,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Capacetes',true,now()),
(102542,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Painéis e Velocímetros',true,now()),
(102543,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Intercomunicadores',true,now()),
(102544,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Viseiras de Capacete',true,now()),
(102545,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Para-brisas',true,now()),
(102546,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Deslizadores de Estrutura',true,now()),
(102547,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Alforges',true,now()),
(102548,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Protetores de Mão',true,now()),
(102549,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Mochilas',true,now()),
(102550,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Adesivos e Emblemas',true,now()),
(102551,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Outros',true,now()),
(102597,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Adesivos e Emblemas',true,now()),
(102598,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Painéis e Velocímetros',true,now()),
(102610,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Phone Holders',true,now()),
(102611,'Peças e Acessórios para Veículos','Acessórios para Motocicletas','','Motorcycle Helmet Camera',true,now()),
(102561,'Peças e Acessórios para Veículos','Pneus e Rodas','','Rodas de Motocicletas',true,now()),
(102607,'Peças e Acessórios para Veículos','Motocicletas','','Motocicletas',true,now())
ON CONFLICT ("id") DO NOTHING;

-- Primeiro vinculo confirmado manualmente (testado e funcionando no BM03_0119).
INSERT INTO "CategoriaVinculoMarketplace" ("categoriaBlingId","marketplace","codigoExterno","descricaoExterno","atualizadoEm")
VALUES (10663241, 'shopee', '102439', 'Bengalas', now())
ON CONFLICT ("categoriaBlingId","marketplace") DO NOTHING;
