[build]
builder = "NIXPACKS"
buildCommand = "PLAYWRIGHT_BROWSERS_PATH=0 npm install && PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install --with-deps chromium && npx prisma generate && npm run build"

[deploy]
startCommand = "PLAYWRIGHT_BROWSERS_PATH=0 npx prisma migrate deploy && npm run start"
restartPolicyType = "ON_FAILURE"
