ALTER TABLE "BlingConfig" ADD COLUMN IF NOT EXISTS "exibirBuscarProdutos" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "BlingConfig" ADD COLUMN IF NOT EXISTS "exibirCompararCSV" BOOLEAN NOT NULL DEFAULT true;
