ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "magaluItemId" TEXT;
ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "magaluLink" TEXT;
ALTER TABLE "Peca" ADD COLUMN IF NOT EXISTS "magaluCategoriaId" TEXT;
ALTER TABLE "BlingConfig" ADD COLUMN IF NOT EXISTS "magaluLojaId" INTEGER DEFAULT 206315662;
