ALTER TABLE "BlingConfig" ADD COLUMN IF NOT EXISTS "nuvemshopAtiva"  BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "BlingConfig" ADD COLUMN IF NOT EXISTS "nuvemshopLojaId" INTEGER NOT NULL DEFAULT 205449158;
